# Couldn't automatically generate a config from your source code.
# This is a generic template to serve as a base for your custom config
# See: https://circleci.com/docs/configuration-reference
version: 2.1
jobs:
  test:
    docker:
      - image: cimg/node:21.6.2
    steps:
      - checkout
      # Replace this with a real test runner invocation
      - run:
          name: Run tests
          command: node -v
  build:
    docker:
      - image: cimg/node:21.6.2
    steps:
      - checkout
      # Replace this with steps to build a package, or executable
      - run:
          name: Build an artifact
          command: node -v
workflows:
  example:
    jobs:
      - test
      - build:
          requires:
            - test
